apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o4gef4mqi-python
  janus-idp.io/tekton: o4gef4mqi-python
  backstage.io/kubernetes-id: o4gef4mqi-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o4gef4mqi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
